---
title: "Open Scholarship at SFU"
format: revealjs
brand: _brand.yml
author:
  name: Gracielle Higino, PhD (she/her)
  affiliation: 
    name: Open Science Community Manager, INN    
---

## Who am I? What is this Open Scholarship Initiative?

## Down with the Ivory Tower

> "[...] ~~science~~ *academia* and everyday life cannot and should not be separated."

::: {style="text-align: right"}
*Rosalind Franklin*
::: 

::: {.notes}
- Nothing we do within a university is disconnected from the world outside of it. There are social, political and environmental contexts to everything we do.
- We believe in an academic environment that is aware of its surroundings, and is open to dialogue with the different aspects of our society.
:::

## The open movement ^[[Mozilla and Working Open](https://www.youtube.com/watch?v=quKdaqlR_9w)]

1. Share decision making  

2. Share content  

3. Invite participation  


## The open movement in scholarship practices

*Responsible researchers...*  

- Strive for excellence and *take responsibility*  
- *Respect* the law, research ethics, and professional standards  
- *Support* a culture of *transparency*, *openness*, and honesty towards other researchers and the *public*  
- *Maximise public benefit* and avoid resource waste  


## Open scholarship garden